from datetime import timedelta

try:
    from .ns_config import iso, now_utc
except ImportError:
    from ns_config import iso, now_utc


HOSTS = [
    {
        "id": "host-edge-fw",
        "hostname": "edge-fw-01",
        "ip": "10.10.0.1",
        "os": "Debian 12",
        "role": "Firewall",
        "riskScore": 88,
        "criticality": "critical",
        "lastSeen": iso(now_utc() - timedelta(minutes=2)),
        "alertCount": 7,
        "status": "online",
        "agent": "installed",
    },
    {
        "id": "host-auth",
        "hostname": "auth-gateway-01",
        "ip": "10.10.0.10",
        "os": "Ubuntu 24.04",
        "role": "Authentication",
        "riskScore": 81,
        "criticality": "high",
        "lastSeen": iso(now_utc() - timedelta(minutes=4)),
        "alertCount": 5,
        "status": "online",
        "agent": "installed",
    },
    {
        "id": "host-app",
        "hostname": "app-node-01",
        "ip": "10.10.1.20",
        "os": "Ubuntu 22.04",
        "role": "Application",
        "riskScore": 63,
        "criticality": "high",
        "lastSeen": iso(now_utc() - timedelta(minutes=3)),
        "alertCount": 3,
        "status": "online",
        "agent": "installed",
    },
    {
        "id": "host-db",
        "hostname": "db-core-01",
        "ip": "10.10.2.15",
        "os": "Rocky Linux 9",
        "role": "Database",
        "riskScore": 54,
        "criticality": "critical",
        "lastSeen": iso(now_utc() - timedelta(minutes=7)),
        "alertCount": 2,
        "status": "online",
        "agent": "installed",
    },
    {
        "id": "host-lab",
        "hostname": "lab-client-07",
        "ip": "10.10.3.77",
        "os": "Windows 11",
        "role": "Workstation",
        "riskScore": 72,
        "criticality": "medium",
        "lastSeen": iso(now_utc() - timedelta(minutes=5)),
        "alertCount": 4,
        "status": "online",
        "agent": "missing",
    },
]

ALERTS = [
    {
        "id": "ALT-000101",
        "timestamp": iso(now_utc() - timedelta(minutes=9)),
        "title": "Brute force SSH detected",
        "severity": "critical",
        "status": "open",
        "sourceIP": "185.227.134.41",
        "destIP": "10.10.0.10",
        "hostname": "auth-gateway-01",
        "assignee": "SOC Analyst 1",
        "eta": "20m",
        "mitreTactic": "Credential Access",
        "description": "fail2ban and auth.log show 46 failed SSH attempts from the same source within 6 minutes.",
        "recommendation": "Ban the source IP, disable password login on SSH and verify whether any account was locked.",
        "playbook": "Check /var/log/auth.log, review fail2ban jail state, force key-only SSH and rotate exposed credentials.",
    },
    {
        "id": "ALT-000102",
        "timestamp": iso(now_utc() - timedelta(minutes=16)),
        "title": "Horizontal port scan observed",
        "severity": "high",
        "status": "investigating",
        "sourceIP": "102.219.88.14",
        "destIP": "10.10.0.1",
        "hostname": "edge-fw-01",
        "assignee": "SOC Analyst 2",
        "eta": "45m",
        "mitreTactic": "Discovery",
        "description": "Packetbeat detected one external address probing 18 ports across 7 internal assets.",
        "recommendation": "Drop the source IP on the firewall, confirm exposure of scanned ports and tighten ingress rules.",
        "playbook": "Correlate Packetbeat flows with firewall rules, validate exposed services and close unused ports.",
    },
    {
        "id": "ALT-000103",
        "timestamp": iso(now_utc() - timedelta(minutes=28)),
        "title": "Abnormal outbound DNS burst",
        "severity": "medium",
        "status": "open",
        "sourceIP": "10.10.3.77",
        "destIP": "8.8.8.8",
        "hostname": "lab-client-07",
        "assignee": "Unassigned",
        "eta": None,
        "mitreTactic": "Command and Control",
        "description": "The AI model flagged unusual DNS request volume from lab-client-07 outside normal lab hours.",
        "recommendation": "Inspect active processes on the workstation and review domains queried in the last hour.",
        "playbook": "Collect DNS history, isolate the endpoint if the burst persists and run malware triage.",
    },
    {
        "id": "ALT-000104",
        "timestamp": iso(now_utc() - timedelta(minutes=42)),
        "title": "Privilege escalation pattern",
        "severity": "high",
        "status": "resolved",
        "sourceIP": "10.10.1.20",
        "destIP": "10.10.1.20",
        "hostname": "app-node-01",
        "assignee": "SOC Lead",
        "eta": None,
        "mitreTactic": "Privilege Escalation",
        "description": "System logs show repeated sudo elevation attempts followed by a new service creation.",
        "recommendation": "Review sudoers changes, inspect new services and compare binaries against a trusted baseline.",
        "playbook": "Audit service files, validate package integrity and restore the node from a clean image if needed.",
    },
]

BLOCKED_IPS = {"185.227.134.41"}
TICKETS = []
AI_FINDINGS_BUFFER = []
DEFAULT_PROFILES = [
    {"id": "profile_admin", "name": "Admin P37", "type": "user", "description": "Primary administrator asset group"},
    {"id": "profile_lab", "name": "Lab Blue Team", "type": "team", "description": "Shared classroom and lab systems"},
    {"id": "profile_dmz", "name": "DMZ Services", "type": "service", "description": "Public-facing perimeter systems"},
]
DEFAULT_ASSETS = [
    {"id": "asset_edge_fw", "hostname": "edge-fw-01", "host_id": "host-edge-fw", "ip": "10.10.0.1", "os": "Debian 12", "role": "Firewall", "site": "yaounde-lab", "environment": "prod", "tags": ["linux", "firewall", "dmz"]},
    {"id": "asset_auth", "hostname": "auth-gateway-01", "host_id": "host-auth", "ip": "10.10.0.10", "os": "Ubuntu 24.04", "role": "Authentication", "site": "yaounde-lab", "environment": "prod", "tags": ["linux", "auth", "internal"]},
    {"id": "asset_app", "hostname": "app-node-01", "host_id": "host-app", "ip": "10.10.1.20", "os": "Ubuntu 22.04", "role": "Application", "site": "yaounde-lab", "environment": "prod", "tags": ["linux", "app", "internal"]},
    {"id": "asset_db", "hostname": "db-core-01", "host_id": "host-db", "ip": "10.10.2.15", "os": "Rocky Linux 9", "role": "Database", "site": "yaounde-lab", "environment": "prod", "tags": ["linux", "database", "core"]},
    {"id": "asset_lab", "hostname": "lab-client-07", "host_id": "host-lab", "ip": "10.10.3.77", "os": "Windows 11", "role": "Workstation", "site": "yaounde-lab", "environment": "lab", "tags": ["windows", "workstation", "lab"]},
]
DEFAULT_PROFILE_ASSETS = [
    {"id": "link_admin_auth", "profile_id": "profile_admin", "asset_id": "asset_auth"},
    {"id": "link_admin_edge", "profile_id": "profile_admin", "asset_id": "asset_edge_fw"},
    {"id": "link_lab_client", "profile_id": "profile_lab", "asset_id": "asset_lab"},
    {"id": "link_dmz_edge", "profile_id": "profile_dmz", "asset_id": "asset_edge_fw"},
    {"id": "link_dmz_app", "profile_id": "profile_dmz", "asset_id": "asset_app"},
]
